### ISSUE TITLE
Add README to describe the examples

### ISSUE THREAD

**Issue by stain** [morloc-project/examples#4]
It would be helpful with a README that described these examples a bit more than the current one-liner. Some links to `morloc` and the origin of these workflows would be good.

In particular, instructions on how to run the examples would be useful.

**Comment by arendsee** [comment]
@stain Yeah, the README at root needs more than a header. I'll update it. There is a more detailed README down in the `flu-case-studies` folder. Eventually this repo will contain more examples than just the workflows study, so the top-level README should contain a table of contents and perhaps links to the example-specific READMEs.
